/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as DaftarBengkelRouteImport } from './routes/daftar-bengkel'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as VerifyResetCodeRouteImport } from './routes/verify-reset-code'
import { Route as ShellProfilRouteImport } from './routes/_shell.profil'
import { Route as DaftarBengkelStatusRouteImport } from './routes/daftar-bengkel.status'
import { Route as ResetPasswordNewRouteImport } from './routes/reset-password.new'
import { Route as ShellAdminBookingRouteImport } from './routes/_shell.admin.booking'
import { Route as ShellAdminCsRouteImport } from './routes/_shell.admin.cs'
import { Route as ShellAdminDashboardRouteImport } from './routes/_shell.admin.dashboard'
import { Route as ShellAdminLaporanRouteImport } from './routes/_shell.admin.laporan'
import { Route as ShellAdminMekanikRouteImport } from './routes/_shell.admin.mekanik'
import { Route as ShellAdminPembayaranRouteImport } from './routes/_shell.admin.pembayaran'
import { Route as ShellAdminPengaturanRouteImport } from './routes/_shell.admin.pengaturan'
import { Route as ShellAdminServisRouteImport } from './routes/_shell.admin.servis'
import { Route as ShellAdminSparepartRouteImport } from './routes/_shell.admin.sparepart'
import { Route as ShellAdminStokRouteImport } from './routes/_shell.admin.stok'
import { Route as ShellOwnerAdminRouteImport } from './routes/_shell.owner.admin'
import { Route as ShellOwnerCsRouteImport } from './routes/_shell.owner.cs'
import { Route as ShellOwnerDashboardRouteImport } from './routes/_shell.owner.dashboard'
import { Route as ShellOwnerKeuntunganRouteImport } from './routes/_shell.owner.keuntungan'
import { Route as ShellOwnerPelangganRouteImport } from './routes/_shell.owner.pelanggan'
import { Route as ShellOwnerServisRouteImport } from './routes/_shell.owner.servis'
import { Route as ShellOwnerSparepartRouteImport } from './routes/_shell.owner.sparepart'
import { Route as ShellPelangganBookingRouteImport } from './routes/_shell.pelanggan.booking'
import { Route as ShellPelangganCsRouteImport } from './routes/_shell.pelanggan.cs'
import { Route as ShellPelangganDashboardRouteImport } from './routes/_shell.pelanggan.dashboard'
import { Route as ShellPelangganEstimasiRouteImport } from './routes/_shell.pelanggan.estimasi'
import { Route as ShellPelangganKendaraanRouteImport } from './routes/_shell.pelanggan.kendaraan'
import { Route as ShellPelangganPembayaranRouteImport } from './routes/_shell.pelanggan.pembayaran'
import { Route as ShellPelangganRiwayatRouteImport } from './routes/_shell.pelanggan.riwayat'
import { Route as ShellPelangganStatusRouteImport } from './routes/_shell.pelanggan.status'
import { Route as ShellSuperadminCsRouteImport } from './routes/_shell.superadmin.cs'
import { Route as ShellSuperadminDashboardRouteImport } from './routes/_shell.superadmin.dashboard'
import { Route as ShellSuperadminErrorLogRouteImport } from './routes/_shell.superadmin.error-log'
import { Route as ShellSuperadminKlienRouteImport } from './routes/_shell.superadmin.klien'
import { Route as ShellSuperadminPengajuanBengkelRouteImport } from './routes/_shell.superadmin.pengajuan-bengkel'
import { Route as AdminUndanganTokenRouteImport } from './routes/admin.undangan.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarBengkelRoute = DaftarBengkelRouteImport.update({
  id: '/daftar-bengkel',
  path: '/daftar-bengkel',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyResetCodeRoute = VerifyResetCodeRouteImport.update({
  id: '/verify-reset-code',
  path: '/verify-reset-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellProfilRoute = ShellProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => ShellRoute,
} as any)
const DaftarBengkelStatusRoute = DaftarBengkelStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => DaftarBengkelRoute,
} as any)
const ResetPasswordNewRoute = ResetPasswordNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ResetPasswordRoute,
} as any)
const ShellAdminBookingRoute = ShellAdminBookingRouteImport.update({
  id: '/admin/booking',
  path: '/admin/booking',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminCsRoute = ShellAdminCsRouteImport.update({
  id: '/admin/cs',
  path: '/admin/cs',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminDashboardRoute = ShellAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminLaporanRoute = ShellAdminLaporanRouteImport.update({
  id: '/admin/laporan',
  path: '/admin/laporan',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminMekanikRoute = ShellAdminMekanikRouteImport.update({
  id: '/admin/mekanik',
  path: '/admin/mekanik',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminPembayaranRoute = ShellAdminPembayaranRouteImport.update({
  id: '/admin/pembayaran',
  path: '/admin/pembayaran',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminPengaturanRoute = ShellAdminPengaturanRouteImport.update({
  id: '/admin/pengaturan',
  path: '/admin/pengaturan',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminServisRoute = ShellAdminServisRouteImport.update({
  id: '/admin/servis',
  path: '/admin/servis',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminSparepartRoute = ShellAdminSparepartRouteImport.update({
  id: '/admin/sparepart',
  path: '/admin/sparepart',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminStokRoute = ShellAdminStokRouteImport.update({
  id: '/admin/stok',
  path: '/admin/stok',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOwnerAdminRoute = ShellOwnerAdminRouteImport.update({
  id: '/owner/admin',
  path: '/owner/admin',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOwnerCsRoute = ShellOwnerCsRouteImport.update({
  id: '/owner/cs',
  path: '/owner/cs',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOwnerDashboardRoute = ShellOwnerDashboardRouteImport.update({
  id: '/owner/dashboard',
  path: '/owner/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOwnerKeuntunganRoute = ShellOwnerKeuntunganRouteImport.update({
  id: '/owner/keuntungan',
  path: '/owner/keuntungan',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOwnerPelangganRoute = ShellOwnerPelangganRouteImport.update({
  id: '/owner/pelanggan',
  path: '/owner/pelanggan',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOwnerServisRoute = ShellOwnerServisRouteImport.update({
  id: '/owner/servis',
  path: '/owner/servis',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOwnerSparepartRoute = ShellOwnerSparepartRouteImport.update({
  id: '/owner/sparepart',
  path: '/owner/sparepart',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPelangganBookingRoute = ShellPelangganBookingRouteImport.update({
  id: '/pelanggan/booking',
  path: '/pelanggan/booking',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPelangganCsRoute = ShellPelangganCsRouteImport.update({
  id: '/pelanggan/cs',
  path: '/pelanggan/cs',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPelangganDashboardRoute = ShellPelangganDashboardRouteImport.update({
  id: '/pelanggan/dashboard',
  path: '/pelanggan/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPelangganEstimasiRoute = ShellPelangganEstimasiRouteImport.update({
  id: '/pelanggan/estimasi',
  path: '/pelanggan/estimasi',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPelangganKendaraanRoute = ShellPelangganKendaraanRouteImport.update({
  id: '/pelanggan/kendaraan',
  path: '/pelanggan/kendaraan',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPelangganPembayaranRoute =
  ShellPelangganPembayaranRouteImport.update({
    id: '/pelanggan/pembayaran',
    path: '/pelanggan/pembayaran',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellPelangganRiwayatRoute = ShellPelangganRiwayatRouteImport.update({
  id: '/pelanggan/riwayat',
  path: '/pelanggan/riwayat',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPelangganStatusRoute = ShellPelangganStatusRouteImport.update({
  id: '/pelanggan/status',
  path: '/pelanggan/status',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSuperadminCsRoute = ShellSuperadminCsRouteImport.update({
  id: '/superadmin/cs',
  path: '/superadmin/cs',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSuperadminDashboardRoute =
  ShellSuperadminDashboardRouteImport.update({
    id: '/superadmin/dashboard',
    path: '/superadmin/dashboard',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellSuperadminErrorLogRoute = ShellSuperadminErrorLogRouteImport.update({
  id: '/superadmin/error-log',
  path: '/superadmin/error-log',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSuperadminKlienRoute = ShellSuperadminKlienRouteImport.update({
  id: '/superadmin/klien',
  path: '/superadmin/klien',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSuperadminPengajuanBengkelRoute =
  ShellSuperadminPengajuanBengkelRouteImport.update({
    id: '/superadmin/pengajuan-bengkel',
    path: '/superadmin/pengajuan-bengkel',
    getParentRoute: () => ShellRoute,
  } as any)
const AdminUndanganTokenRoute = AdminUndanganTokenRouteImport.update({
  id: '/admin/undangan/$token',
  path: '/admin/undangan/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/daftar-bengkel': typeof DaftarBengkelRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/verify-reset-code': typeof VerifyResetCodeRoute
  '/profil': typeof ShellProfilRoute
  '/daftar-bengkel/status': typeof DaftarBengkelStatusRoute
  '/reset-password/new': typeof ResetPasswordNewRoute
  '/admin/booking': typeof ShellAdminBookingRoute
  '/admin/cs': typeof ShellAdminCsRoute
  '/admin/dashboard': typeof ShellAdminDashboardRoute
  '/admin/laporan': typeof ShellAdminLaporanRoute
  '/admin/mekanik': typeof ShellAdminMekanikRoute
  '/admin/pembayaran': typeof ShellAdminPembayaranRoute
  '/admin/pengaturan': typeof ShellAdminPengaturanRoute
  '/admin/servis': typeof ShellAdminServisRoute
  '/admin/sparepart': typeof ShellAdminSparepartRoute
  '/admin/stok': typeof ShellAdminStokRoute
  '/owner/admin': typeof ShellOwnerAdminRoute
  '/owner/cs': typeof ShellOwnerCsRoute
  '/owner/dashboard': typeof ShellOwnerDashboardRoute
  '/owner/keuntungan': typeof ShellOwnerKeuntunganRoute
  '/owner/pelanggan': typeof ShellOwnerPelangganRoute
  '/owner/servis': typeof ShellOwnerServisRoute
  '/owner/sparepart': typeof ShellOwnerSparepartRoute
  '/pelanggan/booking': typeof ShellPelangganBookingRoute
  '/pelanggan/cs': typeof ShellPelangganCsRoute
  '/pelanggan/dashboard': typeof ShellPelangganDashboardRoute
  '/pelanggan/estimasi': typeof ShellPelangganEstimasiRoute
  '/pelanggan/kendaraan': typeof ShellPelangganKendaraanRoute
  '/pelanggan/pembayaran': typeof ShellPelangganPembayaranRoute
  '/pelanggan/riwayat': typeof ShellPelangganRiwayatRoute
  '/pelanggan/status': typeof ShellPelangganStatusRoute
  '/superadmin/cs': typeof ShellSuperadminCsRoute
  '/superadmin/dashboard': typeof ShellSuperadminDashboardRoute
  '/superadmin/error-log': typeof ShellSuperadminErrorLogRoute
  '/superadmin/klien': typeof ShellSuperadminKlienRoute
  '/superadmin/pengajuan-bengkel': typeof ShellSuperadminPengajuanBengkelRoute
  '/admin/undangan/$token': typeof AdminUndanganTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/daftar-bengkel': typeof DaftarBengkelRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/verify-reset-code': typeof VerifyResetCodeRoute
  '/profil': typeof ShellProfilRoute
  '/daftar-bengkel/status': typeof DaftarBengkelStatusRoute
  '/reset-password/new': typeof ResetPasswordNewRoute
  '/admin/booking': typeof ShellAdminBookingRoute
  '/admin/cs': typeof ShellAdminCsRoute
  '/admin/dashboard': typeof ShellAdminDashboardRoute
  '/admin/laporan': typeof ShellAdminLaporanRoute
  '/admin/mekanik': typeof ShellAdminMekanikRoute
  '/admin/pembayaran': typeof ShellAdminPembayaranRoute
  '/admin/pengaturan': typeof ShellAdminPengaturanRoute
  '/admin/servis': typeof ShellAdminServisRoute
  '/admin/sparepart': typeof ShellAdminSparepartRoute
  '/admin/stok': typeof ShellAdminStokRoute
  '/owner/admin': typeof ShellOwnerAdminRoute
  '/owner/cs': typeof ShellOwnerCsRoute
  '/owner/dashboard': typeof ShellOwnerDashboardRoute
  '/owner/keuntungan': typeof ShellOwnerKeuntunganRoute
  '/owner/pelanggan': typeof ShellOwnerPelangganRoute
  '/owner/servis': typeof ShellOwnerServisRoute
  '/owner/sparepart': typeof ShellOwnerSparepartRoute
  '/pelanggan/booking': typeof ShellPelangganBookingRoute
  '/pelanggan/cs': typeof ShellPelangganCsRoute
  '/pelanggan/dashboard': typeof ShellPelangganDashboardRoute
  '/pelanggan/estimasi': typeof ShellPelangganEstimasiRoute
  '/pelanggan/kendaraan': typeof ShellPelangganKendaraanRoute
  '/pelanggan/pembayaran': typeof ShellPelangganPembayaranRoute
  '/pelanggan/riwayat': typeof ShellPelangganRiwayatRoute
  '/pelanggan/status': typeof ShellPelangganStatusRoute
  '/superadmin/cs': typeof ShellSuperadminCsRoute
  '/superadmin/dashboard': typeof ShellSuperadminDashboardRoute
  '/superadmin/error-log': typeof ShellSuperadminErrorLogRoute
  '/superadmin/klien': typeof ShellSuperadminKlienRoute
  '/superadmin/pengajuan-bengkel': typeof ShellSuperadminPengajuanBengkelRoute
  '/admin/undangan/$token': typeof AdminUndanganTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/daftar-bengkel': typeof DaftarBengkelRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/verify-reset-code': typeof VerifyResetCodeRoute
  '/_shell/profil': typeof ShellProfilRoute
  '/daftar-bengkel/status': typeof DaftarBengkelStatusRoute
  '/reset-password/new': typeof ResetPasswordNewRoute
  '/_shell/admin/booking': typeof ShellAdminBookingRoute
  '/_shell/admin/cs': typeof ShellAdminCsRoute
  '/_shell/admin/dashboard': typeof ShellAdminDashboardRoute
  '/_shell/admin/laporan': typeof ShellAdminLaporanRoute
  '/_shell/admin/mekanik': typeof ShellAdminMekanikRoute
  '/_shell/admin/pembayaran': typeof ShellAdminPembayaranRoute
  '/_shell/admin/pengaturan': typeof ShellAdminPengaturanRoute
  '/_shell/admin/servis': typeof ShellAdminServisRoute
  '/_shell/admin/sparepart': typeof ShellAdminSparepartRoute
  '/_shell/admin/stok': typeof ShellAdminStokRoute
  '/_shell/owner/admin': typeof ShellOwnerAdminRoute
  '/_shell/owner/cs': typeof ShellOwnerCsRoute
  '/_shell/owner/dashboard': typeof ShellOwnerDashboardRoute
  '/_shell/owner/keuntungan': typeof ShellOwnerKeuntunganRoute
  '/_shell/owner/pelanggan': typeof ShellOwnerPelangganRoute
  '/_shell/owner/servis': typeof ShellOwnerServisRoute
  '/_shell/owner/sparepart': typeof ShellOwnerSparepartRoute
  '/_shell/pelanggan/booking': typeof ShellPelangganBookingRoute
  '/_shell/pelanggan/cs': typeof ShellPelangganCsRoute
  '/_shell/pelanggan/dashboard': typeof ShellPelangganDashboardRoute
  '/_shell/pelanggan/estimasi': typeof ShellPelangganEstimasiRoute
  '/_shell/pelanggan/kendaraan': typeof ShellPelangganKendaraanRoute
  '/_shell/pelanggan/pembayaran': typeof ShellPelangganPembayaranRoute
  '/_shell/pelanggan/riwayat': typeof ShellPelangganRiwayatRoute
  '/_shell/pelanggan/status': typeof ShellPelangganStatusRoute
  '/_shell/superadmin/cs': typeof ShellSuperadminCsRoute
  '/_shell/superadmin/dashboard': typeof ShellSuperadminDashboardRoute
  '/_shell/superadmin/error-log': typeof ShellSuperadminErrorLogRoute
  '/_shell/superadmin/klien': typeof ShellSuperadminKlienRoute
  '/_shell/superadmin/pengajuan-bengkel': typeof ShellSuperadminPengajuanBengkelRoute
  '/admin/undangan/$token': typeof AdminUndanganTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/daftar-bengkel'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/verify-reset-code'
    | '/profil'
    | '/daftar-bengkel/status'
    | '/reset-password/new'
    | '/admin/booking'
    | '/admin/cs'
    | '/admin/dashboard'
    | '/admin/laporan'
    | '/admin/mekanik'
    | '/admin/pembayaran'
    | '/admin/pengaturan'
    | '/admin/servis'
    | '/admin/sparepart'
    | '/admin/stok'
    | '/owner/admin'
    | '/owner/cs'
    | '/owner/dashboard'
    | '/owner/keuntungan'
    | '/owner/pelanggan'
    | '/owner/servis'
    | '/owner/sparepart'
    | '/pelanggan/booking'
    | '/pelanggan/cs'
    | '/pelanggan/dashboard'
    | '/pelanggan/estimasi'
    | '/pelanggan/kendaraan'
    | '/pelanggan/pembayaran'
    | '/pelanggan/riwayat'
    | '/pelanggan/status'
    | '/superadmin/cs'
    | '/superadmin/dashboard'
    | '/superadmin/error-log'
    | '/superadmin/klien'
    | '/superadmin/pengajuan-bengkel'
    | '/admin/undangan/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/daftar-bengkel'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/verify-reset-code'
    | '/profil'
    | '/daftar-bengkel/status'
    | '/reset-password/new'
    | '/admin/booking'
    | '/admin/cs'
    | '/admin/dashboard'
    | '/admin/laporan'
    | '/admin/mekanik'
    | '/admin/pembayaran'
    | '/admin/pengaturan'
    | '/admin/servis'
    | '/admin/sparepart'
    | '/admin/stok'
    | '/owner/admin'
    | '/owner/cs'
    | '/owner/dashboard'
    | '/owner/keuntungan'
    | '/owner/pelanggan'
    | '/owner/servis'
    | '/owner/sparepart'
    | '/pelanggan/booking'
    | '/pelanggan/cs'
    | '/pelanggan/dashboard'
    | '/pelanggan/estimasi'
    | '/pelanggan/kendaraan'
    | '/pelanggan/pembayaran'
    | '/pelanggan/riwayat'
    | '/pelanggan/status'
    | '/superadmin/cs'
    | '/superadmin/dashboard'
    | '/superadmin/error-log'
    | '/superadmin/klien'
    | '/superadmin/pengajuan-bengkel'
    | '/admin/undangan/$token'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/accept-invite'
    | '/daftar-bengkel'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/verify-reset-code'
    | '/_shell/profil'
    | '/daftar-bengkel/status'
    | '/reset-password/new'
    | '/_shell/admin/booking'
    | '/_shell/admin/cs'
    | '/_shell/admin/dashboard'
    | '/_shell/admin/laporan'
    | '/_shell/admin/mekanik'
    | '/_shell/admin/pembayaran'
    | '/_shell/admin/pengaturan'
    | '/_shell/admin/servis'
    | '/_shell/admin/sparepart'
    | '/_shell/admin/stok'
    | '/_shell/owner/admin'
    | '/_shell/owner/cs'
    | '/_shell/owner/dashboard'
    | '/_shell/owner/keuntungan'
    | '/_shell/owner/pelanggan'
    | '/_shell/owner/servis'
    | '/_shell/owner/sparepart'
    | '/_shell/pelanggan/booking'
    | '/_shell/pelanggan/cs'
    | '/_shell/pelanggan/dashboard'
    | '/_shell/pelanggan/estimasi'
    | '/_shell/pelanggan/kendaraan'
    | '/_shell/pelanggan/pembayaran'
    | '/_shell/pelanggan/riwayat'
    | '/_shell/pelanggan/status'
    | '/_shell/superadmin/cs'
    | '/_shell/superadmin/dashboard'
    | '/_shell/superadmin/error-log'
    | '/_shell/superadmin/klien'
    | '/_shell/superadmin/pengajuan-bengkel'
    | '/admin/undangan/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  DaftarBengkelRoute: typeof DaftarBengkelRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
  VerifyResetCodeRoute: typeof VerifyResetCodeRoute
  AdminUndanganTokenRoute: typeof AdminUndanganTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar-bengkel': {
      id: '/daftar-bengkel'
      path: '/daftar-bengkel'
      fullPath: '/daftar-bengkel'
      preLoaderRoute: typeof DaftarBengkelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-reset-code': {
      id: '/verify-reset-code'
      path: '/verify-reset-code'
      fullPath: '/verify-reset-code'
      preLoaderRoute: typeof VerifyResetCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/profil': {
      id: '/_shell/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ShellProfilRouteImport
      parentRoute: typeof ShellRoute
    }
    '/daftar-bengkel/status': {
      id: '/daftar-bengkel/status'
      path: '/status'
      fullPath: '/daftar-bengkel/status'
      preLoaderRoute: typeof DaftarBengkelStatusRouteImport
      parentRoute: typeof DaftarBengkelRoute
    }
    '/reset-password/new': {
      id: '/reset-password/new'
      path: '/new'
      fullPath: '/reset-password/new'
      preLoaderRoute: typeof ResetPasswordNewRouteImport
      parentRoute: typeof ResetPasswordRoute
    }
    '/_shell/admin/booking': {
      id: '/_shell/admin/booking'
      path: '/admin/booking'
      fullPath: '/admin/booking'
      preLoaderRoute: typeof ShellAdminBookingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/cs': {
      id: '/_shell/admin/cs'
      path: '/admin/cs'
      fullPath: '/admin/cs'
      preLoaderRoute: typeof ShellAdminCsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/dashboard': {
      id: '/_shell/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof ShellAdminDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/laporan': {
      id: '/_shell/admin/laporan'
      path: '/admin/laporan'
      fullPath: '/admin/laporan'
      preLoaderRoute: typeof ShellAdminLaporanRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/mekanik': {
      id: '/_shell/admin/mekanik'
      path: '/admin/mekanik'
      fullPath: '/admin/mekanik'
      preLoaderRoute: typeof ShellAdminMekanikRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/pembayaran': {
      id: '/_shell/admin/pembayaran'
      path: '/admin/pembayaran'
      fullPath: '/admin/pembayaran'
      preLoaderRoute: typeof ShellAdminPembayaranRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/pengaturan': {
      id: '/_shell/admin/pengaturan'
      path: '/admin/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof ShellAdminPengaturanRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/servis': {
      id: '/_shell/admin/servis'
      path: '/admin/servis'
      fullPath: '/admin/servis'
      preLoaderRoute: typeof ShellAdminServisRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/sparepart': {
      id: '/_shell/admin/sparepart'
      path: '/admin/sparepart'
      fullPath: '/admin/sparepart'
      preLoaderRoute: typeof ShellAdminSparepartRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/stok': {
      id: '/_shell/admin/stok'
      path: '/admin/stok'
      fullPath: '/admin/stok'
      preLoaderRoute: typeof ShellAdminStokRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/owner/admin': {
      id: '/_shell/owner/admin'
      path: '/owner/admin'
      fullPath: '/owner/admin'
      preLoaderRoute: typeof ShellOwnerAdminRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/owner/cs': {
      id: '/_shell/owner/cs'
      path: '/owner/cs'
      fullPath: '/owner/cs'
      preLoaderRoute: typeof ShellOwnerCsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/owner/dashboard': {
      id: '/_shell/owner/dashboard'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof ShellOwnerDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/owner/keuntungan': {
      id: '/_shell/owner/keuntungan'
      path: '/owner/keuntungan'
      fullPath: '/owner/keuntungan'
      preLoaderRoute: typeof ShellOwnerKeuntunganRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/owner/pelanggan': {
      id: '/_shell/owner/pelanggan'
      path: '/owner/pelanggan'
      fullPath: '/owner/pelanggan'
      preLoaderRoute: typeof ShellOwnerPelangganRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/owner/servis': {
      id: '/_shell/owner/servis'
      path: '/owner/servis'
      fullPath: '/owner/servis'
      preLoaderRoute: typeof ShellOwnerServisRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/owner/sparepart': {
      id: '/_shell/owner/sparepart'
      path: '/owner/sparepart'
      fullPath: '/owner/sparepart'
      preLoaderRoute: typeof ShellOwnerSparepartRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pelanggan/booking': {
      id: '/_shell/pelanggan/booking'
      path: '/pelanggan/booking'
      fullPath: '/pelanggan/booking'
      preLoaderRoute: typeof ShellPelangganBookingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pelanggan/cs': {
      id: '/_shell/pelanggan/cs'
      path: '/pelanggan/cs'
      fullPath: '/pelanggan/cs'
      preLoaderRoute: typeof ShellPelangganCsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pelanggan/dashboard': {
      id: '/_shell/pelanggan/dashboard'
      path: '/pelanggan/dashboard'
      fullPath: '/pelanggan/dashboard'
      preLoaderRoute: typeof ShellPelangganDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pelanggan/estimasi': {
      id: '/_shell/pelanggan/estimasi'
      path: '/pelanggan/estimasi'
      fullPath: '/pelanggan/estimasi'
      preLoaderRoute: typeof ShellPelangganEstimasiRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pelanggan/kendaraan': {
      id: '/_shell/pelanggan/kendaraan'
      path: '/pelanggan/kendaraan'
      fullPath: '/pelanggan/kendaraan'
      preLoaderRoute: typeof ShellPelangganKendaraanRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pelanggan/pembayaran': {
      id: '/_shell/pelanggan/pembayaran'
      path: '/pelanggan/pembayaran'
      fullPath: '/pelanggan/pembayaran'
      preLoaderRoute: typeof ShellPelangganPembayaranRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pelanggan/riwayat': {
      id: '/_shell/pelanggan/riwayat'
      path: '/pelanggan/riwayat'
      fullPath: '/pelanggan/riwayat'
      preLoaderRoute: typeof ShellPelangganRiwayatRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pelanggan/status': {
      id: '/_shell/pelanggan/status'
      path: '/pelanggan/status'
      fullPath: '/pelanggan/status'
      preLoaderRoute: typeof ShellPelangganStatusRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/superadmin/cs': {
      id: '/_shell/superadmin/cs'
      path: '/superadmin/cs'
      fullPath: '/superadmin/cs'
      preLoaderRoute: typeof ShellSuperadminCsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/superadmin/dashboard': {
      id: '/_shell/superadmin/dashboard'
      path: '/superadmin/dashboard'
      fullPath: '/superadmin/dashboard'
      preLoaderRoute: typeof ShellSuperadminDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/superadmin/error-log': {
      id: '/_shell/superadmin/error-log'
      path: '/superadmin/error-log'
      fullPath: '/superadmin/error-log'
      preLoaderRoute: typeof ShellSuperadminErrorLogRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/superadmin/klien': {
      id: '/_shell/superadmin/klien'
      path: '/superadmin/klien'
      fullPath: '/superadmin/klien'
      preLoaderRoute: typeof ShellSuperadminKlienRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/superadmin/pengajuan-bengkel': {
      id: '/_shell/superadmin/pengajuan-bengkel'
      path: '/superadmin/pengajuan-bengkel'
      fullPath: '/superadmin/pengajuan-bengkel'
      preLoaderRoute: typeof ShellSuperadminPengajuanBengkelRouteImport
      parentRoute: typeof ShellRoute
    }
    '/admin/undangan/$token': {
      id: '/admin/undangan/$token'
      path: '/admin/undangan/$token'
      fullPath: '/admin/undangan/$token'
      preLoaderRoute: typeof AdminUndanganTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellProfilRoute: typeof ShellProfilRoute
  ShellAdminBookingRoute: typeof ShellAdminBookingRoute
  ShellAdminCsRoute: typeof ShellAdminCsRoute
  ShellAdminDashboardRoute: typeof ShellAdminDashboardRoute
  ShellAdminLaporanRoute: typeof ShellAdminLaporanRoute
  ShellAdminMekanikRoute: typeof ShellAdminMekanikRoute
  ShellAdminPembayaranRoute: typeof ShellAdminPembayaranRoute
  ShellAdminPengaturanRoute: typeof ShellAdminPengaturanRoute
  ShellAdminServisRoute: typeof ShellAdminServisRoute
  ShellAdminSparepartRoute: typeof ShellAdminSparepartRoute
  ShellAdminStokRoute: typeof ShellAdminStokRoute
  ShellOwnerAdminRoute: typeof ShellOwnerAdminRoute
  ShellOwnerCsRoute: typeof ShellOwnerCsRoute
  ShellOwnerDashboardRoute: typeof ShellOwnerDashboardRoute
  ShellOwnerKeuntunganRoute: typeof ShellOwnerKeuntunganRoute
  ShellOwnerPelangganRoute: typeof ShellOwnerPelangganRoute
  ShellOwnerServisRoute: typeof ShellOwnerServisRoute
  ShellOwnerSparepartRoute: typeof ShellOwnerSparepartRoute
  ShellPelangganBookingRoute: typeof ShellPelangganBookingRoute
  ShellPelangganCsRoute: typeof ShellPelangganCsRoute
  ShellPelangganDashboardRoute: typeof ShellPelangganDashboardRoute
  ShellPelangganEstimasiRoute: typeof ShellPelangganEstimasiRoute
  ShellPelangganKendaraanRoute: typeof ShellPelangganKendaraanRoute
  ShellPelangganPembayaranRoute: typeof ShellPelangganPembayaranRoute
  ShellPelangganRiwayatRoute: typeof ShellPelangganRiwayatRoute
  ShellPelangganStatusRoute: typeof ShellPelangganStatusRoute
  ShellSuperadminCsRoute: typeof ShellSuperadminCsRoute
  ShellSuperadminDashboardRoute: typeof ShellSuperadminDashboardRoute
  ShellSuperadminErrorLogRoute: typeof ShellSuperadminErrorLogRoute
  ShellSuperadminKlienRoute: typeof ShellSuperadminKlienRoute
  ShellSuperadminPengajuanBengkelRoute: typeof ShellSuperadminPengajuanBengkelRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellProfilRoute: ShellProfilRoute,
  ShellAdminBookingRoute: ShellAdminBookingRoute,
  ShellAdminCsRoute: ShellAdminCsRoute,
  ShellAdminDashboardRoute: ShellAdminDashboardRoute,
  ShellAdminLaporanRoute: ShellAdminLaporanRoute,
  ShellAdminMekanikRoute: ShellAdminMekanikRoute,
  ShellAdminPembayaranRoute: ShellAdminPembayaranRoute,
  ShellAdminPengaturanRoute: ShellAdminPengaturanRoute,
  ShellAdminServisRoute: ShellAdminServisRoute,
  ShellAdminSparepartRoute: ShellAdminSparepartRoute,
  ShellAdminStokRoute: ShellAdminStokRoute,
  ShellOwnerAdminRoute: ShellOwnerAdminRoute,
  ShellOwnerCsRoute: ShellOwnerCsRoute,
  ShellOwnerDashboardRoute: ShellOwnerDashboardRoute,
  ShellOwnerKeuntunganRoute: ShellOwnerKeuntunganRoute,
  ShellOwnerPelangganRoute: ShellOwnerPelangganRoute,
  ShellOwnerServisRoute: ShellOwnerServisRoute,
  ShellOwnerSparepartRoute: ShellOwnerSparepartRoute,
  ShellPelangganBookingRoute: ShellPelangganBookingRoute,
  ShellPelangganCsRoute: ShellPelangganCsRoute,
  ShellPelangganDashboardRoute: ShellPelangganDashboardRoute,
  ShellPelangganEstimasiRoute: ShellPelangganEstimasiRoute,
  ShellPelangganKendaraanRoute: ShellPelangganKendaraanRoute,
  ShellPelangganPembayaranRoute: ShellPelangganPembayaranRoute,
  ShellPelangganRiwayatRoute: ShellPelangganRiwayatRoute,
  ShellPelangganStatusRoute: ShellPelangganStatusRoute,
  ShellSuperadminCsRoute: ShellSuperadminCsRoute,
  ShellSuperadminDashboardRoute: ShellSuperadminDashboardRoute,
  ShellSuperadminErrorLogRoute: ShellSuperadminErrorLogRoute,
  ShellSuperadminKlienRoute: ShellSuperadminKlienRoute,
  ShellSuperadminPengajuanBengkelRoute: ShellSuperadminPengajuanBengkelRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface DaftarBengkelRouteChildren {
  DaftarBengkelStatusRoute: typeof DaftarBengkelStatusRoute
}

const DaftarBengkelRouteChildren: DaftarBengkelRouteChildren = {
  DaftarBengkelStatusRoute: DaftarBengkelStatusRoute,
}

const DaftarBengkelRouteWithChildren = DaftarBengkelRoute._addFileChildren(
  DaftarBengkelRouteChildren,
)

interface ResetPasswordRouteChildren {
  ResetPasswordNewRoute: typeof ResetPasswordNewRoute
}

const ResetPasswordRouteChildren: ResetPasswordRouteChildren = {
  ResetPasswordNewRoute: ResetPasswordNewRoute,
}

const ResetPasswordRouteWithChildren = ResetPasswordRoute._addFileChildren(
  ResetPasswordRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  DaftarBengkelRoute: DaftarBengkelRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
  VerifyResetCodeRoute: VerifyResetCodeRoute,
  AdminUndanganTokenRoute: AdminUndanganTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
